version: '3.8'

services:
  service_a:
    build: ./service_a
    ports:
      - "8000:8000"
      - "50051:50051"
    networks:
      - saint_network

  service_c:
    build: ./service_c
    ports:
      - "8002:8002"
      - "50052:50052"
    networks:
      - saint_network

  service_b:
    build: ./service_b
    ports:
      - "8001:8001"
    depends_on:
      - service_a
      - service_c
    networks:
      - saint_network
    environment:
      # ส่งชื่อ Service ไปให้โค้ด Python รู้จัก
      - USER_SERVICE_HOST=service_a
      - ORDER_SERVICE_HOST=service_c

networks:
  saint_network:
    driver: bridge